(function(q){var c=Object({linkFile:function(a){a.match(/.*\.js$/)?document.write('<script type="text/javascript" src="'+a+'">\x3c/script>'):a.match(/.*\.css$/)&&document.write('<link rel="stylesheet" href="'+a+'" type="text/css" />')},TypeData:"",StageData:"",KeyManData:"",AreaData:"",getData:function(a){var b="";"1"==a?b="Http://api.tgnet.com/CommonData/ProjectType?version=201612021642":"2"==a?b="Http://api.tgnet.com/CommonData/ProjectStage?deep=1&version=201612021642":"3"==a?b="Http://api.tgnet.com/CommonData/Keyman?version=201612021642":
"4"==a&&(b="http://api.tgnet.com/CommonData/Area?deep=2&parent=0001");$.ajax({url:b,type:"GET",dataType:"jsonp",success:function(b){b.data?"1"==a?(c.TypeData=b.data.items,c.setType("projectType-main")):"2"==a?(c.StageData=b.data.items,c.setStage("projectStage-main")):"3"==a?(c.KeyManData=b.data.items,c.setKeyMan("projectKeyMan-main")):"4"==a&&(c.AreaData=b.data.items,c.setArea("projectArea-main")):console.log(b.message)}})},setType:function(a){if(c.TypeData){var b=c.TypeData,f=$('<div class="UB-main" id="'+
a+'" />'),e="",d="",g="";$.each(b,function(a){if("其他"!=b[a].name){d='<label title="全选"><input class="checkboxAll" value="'+b[a].no+'" type="checkbox">全选</label>';var c=b[a].subs;$.each(c,function(a){d+='<label title="'+c[a].name+'"><input value="'+c[a].no+'" class="checkboxMonomer" type="checkbox">'+c[a].name+"</label>"});e+='<li><span v-data="'+b[a].name+'" >'+b[a].name+'<div class="UB-optional-sub">'+d+"</div></span></li>"}});g='<div class="UB-optional"><ul>'+e+'</ul><input type="hidden" /></div><div class="UB-selected"><div class="UB-selected-tub"><span>已选择</span> <a href="javascript:;" class="UB-removeAll">清除全部</a> </div><div class="UB-selected-main"></div></div>';
$(".UB-popBox-main").append(f.clone().html(g));c.Event.default(a)}},setStage:function(a){if(c.StageData){var b=c.StageData,f=$('<div class="UB-main" id="'+a+'" />'),e="",d="";$.each(b,function(a,d){e+='<li><label title="'+b[a].name+'"><input value="'+b[a].no+'" class="checkboxMonomer" type="checkbox">'+b[a].name+"</label></li>"});d='<div class="UB-optional"><ul>'+e+'</ul><input type="hidden" /></div><div class="UB-selected"><div class="UB-selected-tub"><span>已选择</span> <a href="javascript:;" class="UB-removeAll">清除全部</a> </div><div class="UB-selected-main"></div></div>';
$(".UB-popBox-main").append(f.clone().html(d));c.Event.default(a)}},setKeyMan:function(a){if(c.KeyManData){var b=c.KeyManData,f=$('<div class="UB-main" id="'+a+'" />'),e="",d="",g="";$.each(b,function(a){d="";var c=b[a].subs;$.each(c,function(a){d+='<label title="'+c[a].name+'"><input value="'+c[a].no+'" class="checkboxMonomer" type="checkbox">'+c[a].name+"</label>"});e+='<li><span v-data="'+b[a].name+'" >'+b[a].name+'<div class="UB-optional-sub">'+d+"</div></span></li>"});g='<div class="UB-optional"><ul>'+
e+'</ul><input type="hidden" /></div><div class="UB-selected"><div class="UB-selected-tub"><span>已选择</span> <a href="javascript:;" class="UB-removeAll">清除全部</a> </div><div class="UB-selected-main"></div></div>';$(".UB-popBox-main").append(f.clone().html(g));c.Event.default(a)}},setArea:function(a){if(c.AreaData){var b=c.AreaData,f=$('<div class="UB-main" id="'+a+'" />'),e="",d="",g="";$.each(b,function(a){d='<label title="全选"><input class="checkboxAll" value="'+b[a].no+'" type="checkbox">全选</label>';
var c=b[a].subs;$.each(c,function(a){d+='<label title="'+c[a].name+'"><input value="'+c[a].no+'" class="checkboxMonomer" type="checkbox">'+c[a].name+"</label>"});e+='<li><span v-data="'+b[a].name+'" >'+b[a].name+'<div class="UB-optional-sub">'+d+"</div></span></li>"});g='<div class="UB-optional"><ul>'+e+'</ul><input type="hidden" /></div><div class="UB-selected" style="display: none;"><div class="UB-selected-tub"><span>已选择</span> <a href="javascript:;" class="UB-removeAll">清除全部</a> </div><div class="UB-selected-main"></div></div>';
$(".UB-popBox-main").append(f.clone().html(g));c.Event.default(a)}},Event:{hover:function(a){a=$("#"+a);a=$(".UB-optional",a);$("span",a).live("mouseenter",function(){var a=$(this).parent(),c=$(a).index()+1;0==c%5?a.addClass("li-right"):1==c%5?a.addClass("li-left"):a.addClass("li-middle")});$("span",a).live("mouseleave",function(){$(this).parent().removeAttr("class")})},addOption:function(a){var b=$(".UB-optional",a),f=a.attr("id");$(":checkbox",b).live("change",function(){var a=$(this),b=a.parents(".UB-main"),
g=a.parents(".UB-optional-sub"),l=a.attr("class"),k=$(".checkboxMonomer",g),h=$(".checkboxMonomer:checked",b);if("projectKeyMan-main"==f&&5<h.length)a.prop("checked",!1);else{if("checkboxAll"==l)k.prop("checked",a.prop("checked"));else if(g){var n=!0;$.each(k,function(a,b){$(b).prop("checked")||(n=!1)});$(".checkboxAll",g).prop("checked",n)}c.Event.sortOption(b)}})},delOption:function(a){$(".UB-selected-list-right a",a).live("click",function(){var a=$(this),f=a.parents(".UB-main"),e=a.parents(".UB-selected-list"),
d=a.attr("num-data"),g=$("[value='"+d.substr(0,12)+"']",f);g.prop("checked")&&g.prop("checked",!1);$("[value='"+d+"']",f).prop("checked",!1);a.remove();1>$("a",e).length&&(e.remove(),c.Event.selectMark(f))});$(".UB-removeAll",a).on("click",function(){if(1==confirm("您确定要删除全部吗？")){var a=$(this).parents(".UB-main");$("[type='checkbox']",a).prop("checked",!1);$(".UB-selected-list",a).remove();c.Event.selectMark(a)}})},selectMark:function(a){$(".UB-optional ul li",a).each(function(a,c){1<=$("input:checked",
c).length?$("span",c).addClass("already"):$("span",c).removeClass("already")})},sortOption:function(a){var b=$(".UB-optional li",a),f=b.length,e=[],d=$(a).attr("id");$(".UB-selected-list",a).remove();if("projectStage-main"==d){for(var d=$(".checkboxMonomer:checked",a),g=d.length,l="",k=0;k<g;k++){var h=$(d[k]),n=h.parent().attr("title"),h=h.val();e.push({ClassName:n,ClassNo:h});l=l+'<a href="javascript:;" num-data="'+h+'">'+n+"</a>"}l&&""!=l&&$(".UB-selected-main",a).append('<div class="UB-selected-list"><span class="UB-selected-list-left">项目阶段：</span> <div class="UB-selected-list-right">'+
l+"</div></div>")}else for(var m=0;m<f;m++){var h=b[m],p=$("span",h).attr("v-data"),d=$(".checkboxMonomer:checked",h),g=d.length,l="",k=$(".checkboxAll:checked",h);if(0<k.length)for(e.push({ClassName:k.parents("span").attr("v-data"),ClassNo:k.val()}),k=0;k<g;k++)h=$(d[k]),n=h.parent().attr("title"),h=h.val(),l=l+'<a href="javascript:;" num-data="'+h+'">'+n+"</a>";else for(k=0;k<g;k++)h=$(d[k]),h.prop("disabled")||(n=h.parent().attr("title"),h=h.val(),e.push({ClassName:n,ClassNo:h}),l=l+'<a href="javascript:;" num-data="'+
h+'">'+n+"</a>");l&&""!=l&&$(".UB-selected-main",a).append('<div class="UB-selected-list"><span class="UB-selected-list-left">'+p+'：</span> <div class="UB-selected-list-right">'+l+"</div></div>")}1<=e.length?$("[type='hidden']",a).val(_.jsonStringify(e)):$("[type='hidden']",a).val("");c.Event.selectMark(a)},default:function(a){"projectStage-main"!=a&&c.Event.hover(a);a=$("#"+a);c.Event.addOption(a);c.Event.delOption(a)}},setsubmit:function(a,b){$(".UB-popBox-bottom a").bind("click",function(){var f=
$(this),e=f.parents(".UB-popBox"),e=$(".UB-popBox-main",e).data("mainID"),d=$("#"+e),f=f.data("triggerID"),e="";c.Event.sortOption(d);d=$("[type='hidden']",d).val();if(""==d)b?($('[name="'+f+'"]').val(d),$("#"+f).text("点击进行选择").attr("title","点击进行选择"),$(".UB-background").hide(),$(".UB-popBox").hide()):$(".UB-popBox-title").css("color","red");else{$('[name="'+f+'"]').val(d);d&&(d=JSON.parse(d));for(var g=0;g<d.length;g++)e=e+d[g].ClassName+"、";e=e.substr(0,e.length-1);$("#"+f).text(e).attr("title",
e);$(".UB-background").hide();$(".UB-popBox").hide();a&&""!=a&&a()}})},init:function(a,b,f){var e=_.jsonParse($("[name='"+a+"']").val()),d="";if(e){for(var g=0;g<e.length;g++)d=d+e[g].ClassName+"、";e=d.substr(0,d.length-1);$("#"+a).text(e).attr("title",e);f&&""!=f&&f()}$("#"+a).bind("click",function(){var d=_.jsonParse($("[name='"+a+"']").val()),e=1==b?"projectType-main":2==b?"projectStage-main":3==b?"projectKeyMan-main":4==b?"projectArea-main":"",g=1==b?"请选择项目类型":2==b?"请选择项目阶段":3==b?"请选择关键人(最多五项)":
4==b?"请选择业务地区":"",f=$("#"+e);$('[type="checkbox"]',f).prop("checked",!1);if(d){for(var m=0;m<d.length;m++){$("[value='"+d[m].ClassNo+"']",f).prop("checked",!0);if(12==d[m].ClassNo.length&&"projectStage-main"!=e&&"projectArea-main"!=e){var p=$("[value='"+d[m].ClassNo+"']",f).parents(".UB-optional-sub");$(".checkboxMonomer",p).prop("checked",!0)}8==d[m].ClassNo.length&&"projectArea-main"==e&&(p=$("[value='"+d[m].ClassNo+"']",f).parents(".UB-optional-sub"),$(".checkboxMonomer",p).prop("checked",!0))}c.Event.sortOption(f)}$(".UB-main").hide();
$(".UB-background").show();$(".UB-popBox").show();$(".UB-popBox-title").text(g).css("color","#555");$(".UB-popBox-main").removeData("mainID").data("mainID",e);$(".UB-popBox-submit").removeData("triggerID").data("triggerID",a);$("#"+e).show()})}});c.linkFile("http://css.tgimg.cn/Common/userBusiness.css");q.UserBusiness=function(a,b,f,e,d){if(!a)return console.log("必须传入两个参数，第一个触发器的ID，第二是类型。"),!1;var g=$("<div/>");1>$(".UB-background").length&&$("body").append(g.clone().addClass("UB-background"));1>
$(".UB-popBox").length&&($("body").append(g.clone().addClass("UB-popBox").html('<div class="UB-popBox-top"><div class="UB-popBox-title">请选择适合您跟进的项目类型</div><a class="UB-close-box" href="javascript:;"></a></div><div class="UB-popBox-main"></div><div class="UB-popBox-bottom"><a class="UB-popBox-submit" href="javascript:;">确定</a></div>')),c.setsubmit(e,d),$(".UB-close-box").bind("click",function(){$(".UB-background").hide();$(".UB-popBox").hide()}));"1"==b?c.TypeData||c.getData(b):"2"==b?c.StageData||
c.getData(b):"3"==b?c.KeyManData||c.getData(b):"4"==b?c.AreaData||c.getData(b):console.log("必须传入第二参数，1代表项目类型，2代表项目阶段，3代表关键人,4代表业务地区");c.init(a,b,f)}})(window);
