spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/no3?useUnicode=true&characterEncoding=UTF-8
      password: 123456
      username: root

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    cn:
      jiangong:
        mapper:
          debug
server:
  port: 8081
