spring:
  mvc:
    view:
      #prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/no3
    password: 123456
    username: root

mybatis:
  config-location: classpath:mybatis-config.xml

logging:
  level:
    cn:
      jiangong:
        mapper:
          debug

